### ISSUE TITLE
Consider moving *join functions out of pmdplyr

### ISSUE THREAD

**Issue by philip-khor** [NickCH-K/pmdplyr#45]
Low priority issue, but I was thinking that the two-table verbs (inexact and safe joins) in this package are useful for most tabular data, and not specifically panel data. It may make more sense for them to be placed in a separate package later on, which pmdplyr could import for convenience.

**Comment by NickCH-K** [comment]
I was thinking about their general usefulness too. I generally come down on the side of it being good to have more stuff in a single place, e.g. bigger packages, rather than splitting stuff up, especially given that `inexact_join`, while applicable everywhere, I think is most often useful for panels which have a time element (I think most inexact-matching use cases want a time element). Makes things easier to find and use. Is there a strong reason to split it up?

**Comment by philip-khor** [comment]
> I was thinking about their general usefulness too. I generally come down on the side of it being good to have more stuff in a single place, e.g. bigger packages, rather than splitting stuff up, especially given that `inexact_join`, while applicable everywhere, I think is most often useful for panels which have a time element (I think most inexact-matching use cases want a time element). Makes things easier to find and use. Is there a strong reason to split it up?

Not really, no, but I think it may make it easier to market to the broader community beyond panel-data users. 

While the tidyverse developers do tend to split up functions from packages a lot, dplyr does contain functions for both one-table and two-table verbs, so I'm a bit split about this. 

I think having it in a separate package will also give a bit more space for experimentation. Something I was thinking about was that we might want to have `expect` as an argument to the two-table verbs instead of (or complementing?) separate safe_ functions: 

```r
df1 %>% 
  left_join(df2, by = c(x1 = "x2"), expect = "1:1")
```

or something similar. I'm not sure if this is a good idea. 

See also https://github.com/dgrtwo/fuzzyjoin for inexact joins.

**Comment by NickCH-K** [comment]
I don't think I like having `expect` in the verbs themselves, if only because it introduces a bunch of naming conflicts - if you load `pmdplyr` and then `dplyr` for some reason, then `expect` doesn't work any more. This makes sense for something like `tidylog` but is a bit more of a stretch for `pmdplyr`. 

`fuzzyjoin` is interesting! It appears to be thinking more along the lines of matching rather than merging, which conveniently doesn't overlap too strictly with what we're doing.

I can see the justification for it attracting more people who don't use panel data to the joins, but I think in general if someone wants a functionality they'll happily take just that bit from a bigger package; for example people just using `zoo` for `na.locf`, `plm` for `lag`, or `erer` for ordered model marginal effects.

**Comment by philip-khor** [comment]
Hmm alright then, I'll just close this issue.
